# config.yaml

data_source:
  s3:
    region: "us-east-1"
    bucket: "default-s3-bucket"
    object_prefix: "sandbox/transactions_processed_parquet/"

pipeline:
  target_column: "is_fraud"
  test_size: 0.2
  random_state: 42
  resampling_method: "smote" # 'none', 'smote', 'undersample'

training:
  model_params:
    LogisticRegression:
      max_iter: 1500
      solver: 'liblinear'
      C: 1.0
    RandomForest:
      n_estimators: 150
      max_depth: 12
      min_samples_split: 4
      min_samples_leaf: 2
    XGBoost:
      use_label_encoder: false
      n_estimators: 120
      learning_rate: 0.1
      max_depth: 5
      subsample: 0.8
      colsample_bytree: 0.8
    LightGBM:
      n_estimators: 120
      learning_rate: 0.05
      num_leaves: 31
      max_depth: -1

mlflow_config:
  tracking_uri: "http://mlflow-server:5500"
  experiment_name: "Fraud Detection Multi-Model S3"